export default function Head() {
   return (
     <>
       <title>Orhanflix</title>
       <meta content="width=device-width, initial-scale=1" name="viewport" />
       <meta
         name="description"
         content="Generated by create next app batuberque"
       />
       <link rel="icon" href="/vercel.svg" />
     </>
   )
 }
 